---
title: "About me"
description: |
 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I am a graduate student in the Master of Environmental Data Science program at the Bren School of Environmental Science and Management at UC Santa Barbara. I am an Army veteran. During my time in the Army, from 2010 to 2018, I began to develop an interest in the environment and environmental issues. My experiences overseas taught me the importance of these issues and their connection to politics, society, security, and overall stability. After the Army, I went back to school and received my bachelor’s degree in Geosciences from the University of Wisconsin – Parkside in 2020. During my undergraduate education, I was able to participate in multiple research projects in the areas of hydrology and hydrogeology. As a graduate student, I am learning to apply new tools and methods to help solve the environmental problems of the present and future. I look forward to applying this knowledge to new projects and challenges. 
